<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper/helper.proto

namespace GPBMetadata\Helper;

class Helper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2010a1368656c7065722f68656c7065722e70726f746f22190a094964" .
            "52657175657374120c0a04636f6465180120012805221c0a0a4964526573" .
            "706f6e7365120e0a06726573756c7418012001280332340a0648656c7065" .
            "72122a0a0f476574446973747269627574654964120a2e49645265717565" .
            "73741a0b2e4964526573706f6e73654214ca02114d6963726f50726f746f" .
            "5c48656c706572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

