<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper/helper.proto

namespace GPBMetadata\Helper;

class Helper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6010a1368656c7065722f68656c7065722e70726f746f12114d696372" .
            "6f50726f746f2e48656c70657222180a09496452657175657374120b0a03" .
            "6e756d180120012805221c0a0a4964526573706f6e7365120e0a06726573" .
            "756c74180120012803325c0a0648656c70657212520a0f47657444697374" .
            "7269627574654964121c2e4d6963726f50726f746f2e48656c7065722e49" .
            "64526571756573741a1d2e4d6963726f50726f746f2e48656c7065722e49" .
            "64526573706f6e736528013001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

