<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper/helper.proto

namespace GPBMetadata\Helper;

class Helper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3010a1368656c7065722f68656c7065722e70726f746f12114d696372" .
            "6f50726f746f2e48656c70657222190a09496452657175657374120c0a04" .
            "636f6465180120012805221c0a0a4964526573706f6e7365120e0a067265" .
            "73756c7418012001280332580a0648656c706572124e0a0f476574446973" .
            "747269627574654964121c2e4d6963726f50726f746f2e48656c7065722e" .
            "4964526571756573741a1d2e4d6963726f50726f746f2e48656c7065722e" .
            "4964526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

