<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/helper/helper.proto

namespace GPBMetadata\Pb\Helper;

class Helper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f010a1670622f68656c7065722f68656c7065722e70726f746f22190a" .
            "09496452657175657374120c0a04636f6465180120012805221c0a0a4964" .
            "526573706f6e7365120e0a06726573756c7418012001280332340a064865" .
            "6c706572122a0a0f476574446973747269627574654964120a2e49645265" .
            "71756573741a0b2e4964526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

