<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/helper/helper.proto

namespace GPBMetadata\Proto\Helper;

class Helper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92010a1970726f746f2f68656c7065722f68656c7065722e70726f746f" .
            "22190a09496452657175657374120c0a04636f6465180120012805221c0a" .
            "0a4964526573706f6e7365120e0a06726573756c7418012001280332340a" .
            "0648656c706572122a0a0f476574446973747269627574654964120a2e49" .
            "64526571756573741a0b2e4964526573706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

