# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper/helper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helper/helper.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\312\002\021MicroProto\\Helper'),
  serialized_pb=_b('\n\x13helper/helper.proto\"\x19\n\tIdRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x1c\n\nIdResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32\x34\n\x06Helper\x12*\n\x0fGetDistributeId\x12\n.IdRequest\x1a\x0b.IdResponseB\x14\xca\x02\x11MicroProto\\Helperb\x06proto3')
)




_IDREQUEST = _descriptor.Descriptor(
  name='IdRequest',
  full_name='IdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='IdRequest.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=48,
)


_IDRESPONSE = _descriptor.Descriptor(
  name='IdResponse',
  full_name='IdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='IdResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['IdRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['IdResponse'] = _IDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdRequest = _reflection.GeneratedProtocolMessageType('IdRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDREQUEST,
  '__module__' : 'helper.helper_pb2'
  # @@protoc_insertion_point(class_scope:IdRequest)
  })
_sym_db.RegisterMessage(IdRequest)

IdResponse = _reflection.GeneratedProtocolMessageType('IdResponse', (_message.Message,), {
  'DESCRIPTOR' : _IDRESPONSE,
  '__module__' : 'helper.helper_pb2'
  # @@protoc_insertion_point(class_scope:IdResponse)
  })
_sym_db.RegisterMessage(IdResponse)


DESCRIPTOR._options = None

_HELPER = _descriptor.ServiceDescriptor(
  name='Helper',
  full_name='Helper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=80,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDistributeId',
    full_name='Helper.GetDistributeId',
    index=0,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=_IDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELPER)

DESCRIPTOR.services_by_name['Helper'] = _HELPER

# @@protoc_insertion_point(module_scope)
