# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper/helper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helper/helper.proto',
  package='MicroProto.Helper',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13helper/helper.proto\x12\x11MicroProto.Helper\"\x18\n\tIdRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1c\n\nIdResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32\\\n\x06Helper\x12R\n\x0fGetDistributeId\x12\x1c.MicroProto.Helper.IdRequest\x1a\x1d.MicroProto.Helper.IdResponse(\x01\x30\x01\x62\x06proto3')
)




_IDREQUEST = _descriptor.Descriptor(
  name='IdRequest',
  full_name='MicroProto.Helper.IdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='MicroProto.Helper.IdRequest.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=66,
)


_IDRESPONSE = _descriptor.Descriptor(
  name='IdResponse',
  full_name='MicroProto.Helper.IdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MicroProto.Helper.IdResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['IdRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['IdResponse'] = _IDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdRequest = _reflection.GeneratedProtocolMessageType('IdRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDREQUEST,
  '__module__' : 'helper.helper_pb2'
  # @@protoc_insertion_point(class_scope:MicroProto.Helper.IdRequest)
  })
_sym_db.RegisterMessage(IdRequest)

IdResponse = _reflection.GeneratedProtocolMessageType('IdResponse', (_message.Message,), {
  'DESCRIPTOR' : _IDRESPONSE,
  '__module__' : 'helper.helper_pb2'
  # @@protoc_insertion_point(class_scope:MicroProto.Helper.IdResponse)
  })
_sym_db.RegisterMessage(IdResponse)



_HELPER = _descriptor.ServiceDescriptor(
  name='Helper',
  full_name='MicroProto.Helper.Helper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=98,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDistributeId',
    full_name='MicroProto.Helper.Helper.GetDistributeId',
    index=0,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=_IDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELPER)

DESCRIPTOR.services_by_name['Helper'] = _HELPER

# @@protoc_insertion_point(module_scope)
