<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image/image.proto

namespace GPBMetadata\Image;

class Image
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a11696d6167652f696d6167652e70726f746f1205696d61676522" .
            "450a1155706c6f616446696c6552657175657374120c0a0466696c651801" .
            "2001280c12100a0866696c654e616d6518022001280912100a0866696c65" .
            "5479706518032001280d22340a1255706c6f616446696c65526573706f6e" .
            "7365120c0a04636f646518012001280d12100a0866696c65506174681802" .
            "20012809324e0a05496d61676512450a0a55706c6f616446696c6512182e" .
            "696d6167652e55706c6f616446696c65526571756573741a192e696d6167" .
            "652e55706c6f616446696c65526573706f6e7365280130014213ca02104d" .
            "6963726f50726f746f5c496d616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

