// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/helper/helper.proto

package helper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Helper service

type HelperService interface {
	GetDistributeId(ctx context.Context, in *IdRequest, opts ...client.CallOption) (*IdResponse, error)
}

type helperService struct {
	c    client.Client
	name string
}

func NewHelperService(name string, c client.Client) HelperService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "helper"
	}
	return &helperService{
		c:    c,
		name: name,
	}
}

func (c *helperService) GetDistributeId(ctx context.Context, in *IdRequest, opts ...client.CallOption) (*IdResponse, error) {
	req := c.c.NewRequest(c.name, "Helper.GetDistributeId", in)
	out := new(IdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Helper service

type HelperHandler interface {
	GetDistributeId(context.Context, *IdRequest, *IdResponse) error
}

func RegisterHelperHandler(s server.Server, hdlr HelperHandler, opts ...server.HandlerOption) error {
	type helper interface {
		GetDistributeId(ctx context.Context, in *IdRequest, out *IdResponse) error
	}
	type Helper struct {
		helper
	}
	h := &helperHandler{hdlr}
	return s.Handle(s.NewHandler(&Helper{h}, opts...))
}

type helperHandler struct {
	HelperHandler
}

func (h *helperHandler) GetDistributeId(ctx context.Context, in *IdRequest, out *IdResponse) error {
	return h.HelperHandler.GetDistributeId(ctx, in, out)
}
