<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idProduce/idProduce.proto

namespace MicroProto\IdProduce;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>idProduce.IdProduceRequest</code>
 */
class IdProduceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 len = 1;</code>
     */
    private $len = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $len
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\IdProduce\IdProduce::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 len = 1;</code>
     * @return int
     */
    public function getLen()
    {
        return $this->len;
    }

    /**
     * Generated from protobuf field <code>uint32 len = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLen($var)
    {
        GPBUtil::checkUint32($var);
        $this->len = $var;

        return $this;
    }

}

