<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idProduce/idProduce.proto

namespace GPBMetadata\IdProduce;

class IdProduce
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7010a19696450726f647563652f696450726f647563652e70726f746f" .
            "1209696450726f64756365221f0a10496450726f64756365526571756573" .
            "74120b0a036c656e18012001280d222e0a11496450726f64756365526573" .
            "706f6e7365120c0a04636f646518012001280d120b0a0369647318022003" .
            "2804325d0a09496450726f6475636512500a0f4765744469737472696275" .
            "74654964121b2e696450726f647563652e496450726f6475636552657175" .
            "6573741a1c2e696450726f647563652e496450726f64756365526573706f" .
            "6e7365280130014217ca02144d6963726f50726f746f5c496450726f6475" .
            "6365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

